---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlvolume
  labels:
    app: mysqlvolume
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldeployment
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mallikharjun.jfrog.io/mallikharjun/mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: malli
            - name: MYSQL_DATABASE
              value: database
            - name: MYSQL_USER
              value: devopsuser
            - name: MYSQL_PASSWORD
              value: malli
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysqlpvc
              mountPath: /var/lib/mysql
      imagepullsecrets:
        - name: downloading
      volumes:
        - name: mysqlpvc
          persistentVolumeClaim:
            claimName: mysqlvolume      